import unittest

from connect_app import driver

# How Zadig (libwdi) writes its driver package for the Mac: the ID goes through a string variable.
ZADIG_INF = r"""
[libusbDevice_WinUSB.NTamd64]
%DeviceName% = USB_Install, USB\%DeviceID%
[USB_Install]
Include = winusb.inf
Needs   = WINUSB.NT
[Strings]
DeviceName = "Mac (Composite Parent)"
DeviceID   = "VID_05AC&PID_1905"
"""


class DriverTests(unittest.TestCase):
    def test_recognises_packages_that_put_winusb_on_the_mac(self):
        self.assertTrue(driver.targets_mac_with_winusb(ZADIG_INF))
        self.assertTrue(driver.targets_mac_with_winusb("%D% = I, USB\\VID_05AC&PID_1905\nAddService = WinUSB"))

    def test_leaves_other_packages_alone(self):
        self.assertFalse(driver.targets_mac_with_winusb(ZADIG_INF.replace("PID_1905", "PID_12A8")))  # an iPhone
        self.assertFalse(driver.targets_mac_with_winusb(ZADIG_INF.replace("PID_1905", "PID_1905&MI_00")))
        self.assertFalse(driver.targets_mac_with_winusb('DeviceID = "VID_05AC&PID_1905"\nAddService = usbser'))
        self.assertFalse(driver.targets_mac_with_winusb("USB\\VID_05AC&PID_19051 WinUSB"))

    def test_recognises_zadig_certificates_for_the_mac_only(self):
        self.assertTrue(driver.is_zadig_mac_certificate("USB\\VID_05AC&PID_1905 (libwdi autogenerated)"))
        self.assertFalse(driver.is_zadig_mac_certificate("USB\\VID_1234&PID_5678 (libwdi autogenerated)"))
        self.assertFalse(driver.is_zadig_mac_certificate("USB\\VID_05AC&PID_1905"))

    def test_macs_and_readiness(self):
        self.assertTrue(driver.is_mac(0x1905, ""))
        self.assertTrue(driver.is_mac(0x1906, "Mac"))
        self.assertFalse(driver.is_mac(0x12A8, "iPhone"))
        self.assertTrue(driver.MacDevice("id", 0x1905, True, "WinUSB", "Mac").ready)
        self.assertFalse(driver.MacDevice("id", 0x1905, True, "usbccgp", "Mac").ready)
        self.assertFalse(driver.Leftovers([], [], []))
        self.assertTrue(driver.Leftovers([], ["oem140.inf"], []))

    def test_this_windows_offers_winusb(self):  # read-only
        self.assertTrue(driver.winusb_available())
        self.assertIsInstance(driver.find_macs(), list)


if __name__ == "__main__":
    unittest.main()
