// Connect App.exe: starts the app with its bundled Python runtime. Windows asks for administrator rights before
// this runs (launcher.manifest), and the app inherits them. tools/build.py compiles two flavours:
//  - folder build: the "runtime" and "app" folders sit next to this exe;
//  - single file (ONEFILE): they're embedded, and unpacked once per version into Program Files\Connect App.
//    Only administrators can write there, so nothing can swap files before the app runs with admin rights
//    (which a user-writable folder such as %TEMP% would allow).
using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text;
using System.Windows.Forms;
#if ONEFILE
using System.IO.Compression;
#endif

[assembly: AssemblyTitle("Connect App")]
[assembly: AssemblyProduct("Connect App")]
[assembly: AssemblyDescription("Connect a Mac to this PC over a USB-C cable")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

static class Launcher
{
    [STAThread]
    static int Main(string[] args)
    {
        try
        {
#if ONEFILE
            if (args.Length == 2 && args[0] == "--extract-only")  // used by the build to check the payload
            {
                Unpack(args[1]);
                return 0;
            }
            return Start(Unpacked(), args);
#else
            return Start(AppDomain.CurrentDomain.BaseDirectory, args);
#endif
        }
        catch (Exception e)
        {
            MessageBox.Show("Connect App couldn't start: " + e.Message, "Connect App", MessageBoxButtons.OK,
                            MessageBoxIcon.Error);
            return 1;
        }
    }

    static int Start(string folder, string[] args)
    {
        string python = Path.Combine(folder, @"runtime\pythonw.exe");
        string script = Path.Combine(folder, @"app\Connect App.pyw");
        if (!File.Exists(python) || !File.Exists(script))
        {
            MessageBox.Show("Connect App is incomplete: keep the 'runtime' and 'app' folders next to Connect App.exe.",
                            "Connect App", MessageBoxButtons.OK, MessageBoxIcon.Error);
            return 1;
        }
        StringBuilder arguments = new StringBuilder("\"" + script + "\"");
        foreach (string arg in args)
        {
            arguments.Append(" \"").Append(arg.Replace("\"", "\\\"")).Append('"');
        }
        ProcessStartInfo start = new ProcessStartInfo(python, arguments.ToString());
        start.UseShellExecute = false;
        start.WorkingDirectory = folder;
        start.EnvironmentVariables.Remove("TCL_LIBRARY");  // another Tcl on the PC must not replace the bundled one
        start.EnvironmentVariables.Remove("TK_LIBRARY");
#if ONEFILE
        start.EnvironmentVariables["CONNECTAPP_UNPACKED"] = folder;  // lets "Remove from this PC" delete it too
#endif
        Process.Start(start);
        return 0;
    }

#if ONEFILE
    // Payload.Id (generated by build.py) names this version; each version is unpacked once.
    static string Unpacked()
    {
        string home = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "Connect App");
        string target = Path.Combine(home, "app-" + Payload.Id);
        if (!File.Exists(Path.Combine(target, ".complete")))
        {
            string staging = target + ".unpacking-" + Guid.NewGuid().ToString("N");
            Unpack(staging);
            try
            {
                if (Directory.Exists(target))
                {
                    Directory.Delete(target, true);  // left over from an interrupted unpack
                }
                Directory.Move(staging, target);
            }
            catch (IOException)
            {
                if (!File.Exists(Path.Combine(target, ".complete")))
                {
                    throw;
                }
                TryDelete(staging);  // another launch finished unpacking first
            }
        }
        foreach (string old in Directory.GetDirectories(home, "app-*"))
        {
            if (Path.GetFileName(old).IndexOf('.') < 0 && !string.Equals(old, target, StringComparison.OrdinalIgnoreCase))
            {
                TryDelete(old);  // earlier versions; skipped while one is still running
            }
        }
        return target;
    }

    static void Unpack(string folder)
    {
        Directory.CreateDirectory(folder);
        using (Stream payload = Assembly.GetExecutingAssembly().GetManifestResourceStream("payload.zip"))
        using (ZipArchive archive = new ZipArchive(payload, ZipArchiveMode.Read))
        {
            archive.ExtractToDirectory(folder);
        }
        File.WriteAllText(Path.Combine(folder, ".complete"), Payload.Id);
    }

    static void TryDelete(string folder)
    {
        try
        {
            Directory.Delete(folder, true);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }
#endif
}
